---

- name: Create WordPress MySQL database
  mysql_db:
    name: "{{ database_name }}"
    state: present
- name: Create WordPress MySQL user
  mysql_user:
    name: "{{ database_user }}"
    host: "{{ item }}"
    password: "{{ database_password }}"
    priv: "{{ database_name }}.*:ALL"
  loop:
    - localhost
    - 192.168.1.38

- name: Does the database exist?
  command: mysql -u root "{{ database_name }}" -e "SELECT ID FROM {{ database_name }}.wp_users LIMIT 1;"
  register: db_exist
  ignore_errors: true
- name: Copy WordPress DB
  template:
    src: wp-database.sql
    dest: /tmp/wp-database.sql
  when: db_exist.rc > 0
- name: Import WordPress DB
  mysql_db:
    target: /tmp/wp-database.sql
    state: import
    name: "{{ database_name }}"
  when: db_exist.rc > 0
