---
- name: Ensure MySQL packages are installed.
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb
    - mariadb-server
    - mariadb-libs
    - MySQL-python
    - perl-DBD-MySQL

- name: Ensure MySQL Python libraries are installed.
  yum:
    name: MySQL-python
    state: present

- name: Generate new root password
  command: openssl rand -hex 7
  args:
    creates: /root/.my.cnf
  register: mysql_new_root_pass

- name: Output new root password
  debug:
    msg: "New root password is {{ mysql_new_root_pass.stdout }}"
  when: mysql_new_root_pass.changed

- name: Remove anonymous users
  mysql_user:
    name: ""
    state: absent
  when: mysql_new_root_pass.changed

- name: Remove test database
  mysql_db:
    name: test
    state: absent
  when: mysql_new_root_pass.changed
