---

# MySQL
- name: Install MySQL on Ubuntu
  package:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-server
    - python-mysqldb
  when: ansible_distribution == 'Ubuntu'

- name: Install MySQL on CentOS - Donwload sources
  get_url:
    url: "https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm"
    dest: /opt/mysql
  when: ansible_distribution == 'CentOS'

- name: Install MySQL on CentOS - Install package
  yum:
    name: /opt/mysql/mysql-community-release-el7-5.noarch.rpm
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install MySQL on CentOS - Install MySQL
  yum: 
    name: mysql-server 
    state: installed
  when: ansible_distribution == 'CentOS'

- name: Generate new root password
  command: openssl rand -hex 7
  args:
    creates: /root/.my.cnf
  register: mysql_new_root_pass

- name: Remove anonymous users
  mysql_user:
    name: ""
    state: absent
  when: mysql_new_root_pass.changed

- name: Remove test database
  mysql_db:
    name: test
    state: absent
  when: mysql_new_root_pass.changed

- name: Output new root password
  debug:
    msg: "New root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed

- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_new_root_pass.stdout }}"
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_new_root_pass.changed

- name: Create my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
  when: mysql_new_root_pass.changed

- name: Create mysqld.cnf
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  when: mysql_new_root_pass.changed
  notify: restart mysql

- name: Open 3306 port
  iptables:
    chain: INPUT
    in_interface: eth0
    protocol: tcp
    destination_port: '3306'
    jump: ACCEPT
  when: mysql_new_root_pass.changed
