---

- name: Installation Wordpress
  become: true
  hosts: wordpress
  roles:
    - role: wp.php
    - role: wp.mysql
    - role: wp.nginx
    - role: wp.wordpress
      database_name: wordpress
      database_user: wordpress
      database_password: bananas
