---

- name: Installation Wordpress
  become: true
  hosts: wordpress
  roles:
    - wp.php
    - wp.mysql
    - wp.nginx
    - wp.wordpress
  tasks:
# TOOLS
    - name: Install required tools
      apt:
        name:
          - unzip
        state: present
