---

- name: Install Dependecies on Pres server
  become: true
  hosts: pres
  roles:
    - role: wp.php
    - role: wp.nginx

- name: Install Dependecies on Data server
  become: true
  hosts: data
  roles:
    - role: wp.mysql

- name: Install wordpress on Pres server
  become: true
  hosts: pres
  role:
    - role: wp.wordpress
      database_name: wordpress
      database_user: wordpress
      database_password: bananas
      wp_domain: book.example.com
      initial_post_title: A que coucou
      initial_post_content: Le wordpress de maurice.
      wp_role: wp_pres

- name: Install wordpress on Data server
  become: true
  hosts: data
  roles:
    - role: wp.wordpress
      database_name: wordpress
      database_user: wordpress
      database_password: bananas
      wp_domain: book.example.com
      initial_post_title: A que coucou
      initial_post_content: Le wordpress de maurice.
      wp_role: wp_data
