---

- name: Installation Wordpress
  become: true
  hosts: wordpress
  roles:
    - role: wp.php
    - role: wp.mysql
    - role: wp.nginx
      wp_domain: book.example.com
    - role: wp.wordpress
      database_name: wordpress
      database_user: wordpress
      database_password: bananas
      wp_domain: book.example.com
      initial_post_title: A que coucou
      initial_post_content: Le wordpress de maurice.
