---

- name: Test ping
  hosts: VM
  become: yes
  tasks:
    - name: ping
      ping:
    # PHP
    - name: Install pre-requisite for PHP 7
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - epel-release
        - yum-utils
        - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - name: Enable remi-php73 repository
      shell: yum-config-manager --enable remi-php73
    - name: Install PHP 7
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - php
        - php-common
        - php-opcache
        - php-mcrypt
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
    # MySQL
    - name: Install mysql-server
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    - name: Enable mysql repository
      shell: yum-config-manager --enable mysql80-community-release-el7-1
    - name: Install mysql-server
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - mysql-server
        - MySQL-python
      # Start and enable DB
    - name: Start and enable DB
      service:
        name: mysqld
        state: started
        enabled: yes
      # Configure DB
    - name: Generate new root password
      command: openssl rand -hex 7
      register: mysql_new_root_pass
    - name: Remove anonymous users
      mysql_user: name="" state=absent
    - name: Remove test database
      mysql_db: name=test state=absent
