---

- name: Test ping
  hosts: VM
  become: yes
  tasks:
    - name: ping
      ping:
    # PHP
    - name: Install PHP
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - php
        - php-fpm
        - php-mysql
        - php-xml
