---

- name: Test ping
  hosts: VM
  become: yes
  tasks:
    - name: ping
      ping:
    # PHP
    - name: Install pre-requisite for PHP 7
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - epel-release
        - yum-utils
        - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - name: Enable remi-php73 repository
      shell: yum-config-manager --enable remi-php73
    - name: Install PHP 7
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - php
        - php-common
        - php-opcache
        - php-mcrypt
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
    # MySQL
    - name: Get mysql repository
      get_url:
        url: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        dest: /tmp
    - name: Enable remi-php73 repository
      shell: rpm -Uvh /tmp/mysql80-community-release-el7-1.noarch.rpm
