---

- name: Test ping
  hosts: VM
  become: yes
  tasks:
    - name: ping
      ping:
    # PHP
    - name: Install pre-requisite for PHP 7
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - epel-release
        - yum-utils
        - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - name: Enable remi-php73 repository
      shell: sudo yum-config-manager --enable remi-php73
