---
#
# Attention au /etc/resolv.conf qui peut-être vide
# Après l'avoir implémenté de servername 8.8.8.8 => yum clean all & yum update
#
# - name: "Clean and update yum"
#   command: "{{ yum_command }}"
#   loop:
#     - yum clean all
#     - yum update
#   loop_control:
#     loop_var: yum_command

- name: Ensure repository is installed
  package:
    name: "epel-release"
    state: present

- name: "remi repo activation"
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: "install php72 packages"
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "remi-php72"
  loop:
    - php
    - php-cli
    - php-fpm
    - php-mysql
    - php-json
    - php-opcache
    - php-mbstring
    - php-xml
    - php-gd
    - php-curl
    - libselinux-python

- name: Remove httpd
  package:
    name: httpd
    state: absent

- name: Update /etc/php-fpm.d/www.conf
  template:
    src: www.conf.j2
    dest: /etc/php-fpm.d/www.conf
  notify: restart php-fpm

- name: Update user and group for /var/lib/php
  file:
    state: directory
    path: "/var/lib/php"
    owner: root
    group: nginx
    recurse: yes
  notify: restart php-fpm

- name: Enable php-FPM
  service:
    name: php-fpm
    state: enabled
