---

# - name: "Clean and update yum"
#   command: "{{ yum_command }}"
#   loop:
#     - yum clean all
#     - yum update
#   loop_control:
#     loop_var: yum_command

- name: Ensure repository is installed
  package:
    name: "epel-release"
    state: present

- name: "remi repo activation"
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: "install php74 packages"
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "remi-php74"
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-xml

- name: Remove httpd
  package:
    name: httpd
    state: absent
