---
# PHP
- name: Add the ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
  when: ansible_distribution == 'Ubuntu'

- name: Ensure repository is installed
  package:
    name: "epel-release"
    state: present
  when: ansible_distribution == 'CentOS'

- name: "remi repo activation"
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  when: ansible_distribution == 'CentOS'

- name: "install php70 packages"
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "remi-php74"
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-xml
  when: ansible_distribution == 'CentOS'

- name: Install PHP
  package:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-xml
  when: ansible_distribution == 'Ubuntu'

- name: Remove apache2
  package:
    name: apache2
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Remove httpd
  package:
    name: httpd
    state: absent
  when: ansible_distribution == 'CentOS'
