---
# PHP
- name: Add the ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
- name: Install PHP
  apt:
    name: "{{ item }}"
      # - php
      # - php-fpm
      # - php-mysql
      # - php-xml
      # - python-apt
    state: present
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-xml
    - python-apt

- name: Remove apache2
  apt:
    name: apache2
    state: absent
