---
# PHP
- name: Add the ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
- name: Install PHP
  apt:
    name:
      - php
      - php-fpm
      - php-mysql
      - php-xml
      - python-apt
    state: present
- name: Remove apache2
  apt:
    name: apache2
    state: absent
