---
# PHP
- name: Install PHP on Pres
  import_tasks: CentOS.yml
  when: ansible_distribution == 'CentOS'

- name: Install PHP on Pres
  import_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'