---

# Ignore errors en cas de pb de mise à jour du repo
- name: Add the ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: true

- name: Install PHP
  package:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-xml
    - python-apt
  when: ansible_distribution == 'Ubuntu'

- name: Remove apache2
  package:
    name: apache2
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Check PHP version
  find:
    paths: /etc/php
    file_type: directory
    patterns: '7.*'
  register: php_version

- debug:
    var: php_version.files[0].path.split("/")[2]
