---
# nginx
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Install libselinux-python
  package: 
    name: libselinux-python
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Create nginx config
  template:
    src: default.j2
    dest: /etc/nginx/conf.d/default
  notify: restart nginx
