---
# nginx
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Install libselinux-python
  package:
    name: libselinux-python
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Create nginx config
  template:
    src: default_CentOS.j2
    dest: /etc/nginx/conf.d/default
  notify: restart nginx

- name: Update user and group for /var/lib/php
  file:
    state: directory
    path: "/var/lib/php"
    owner: root
    group: nginx
    recurse: yes

- name: Restart php-FPM
  service:
    name: php-fpm
    state: restarted
