---
# nginx
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Create nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  when: ansible_distribution == 'Ubuntu'

- name: Create nginx config
  template:
    src: default.j2
    dest: /etc/nginx/conf.d/{{ wp_domain }}.conf
  notify: restart nginx
  when: ansible_distribution == 'CentOS'
