---
# nginx
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Install libselinux-python
  package:
    name: libselinux-python
    state: present
  when: ansible_distribution == 'CentOS'

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Check PHP version
  command: php --version
  register: php_version

- debug:
    var: php_version.stdout

- set_fact:
    fpm_sock: /run/php-fpm/www.sock
  when: ansible_distribution == 'CentOS'

- set_fact:
    fpm_sock: /run/php/php7.{{ php_version.stdout.split(" ")[1].split(".")[1] }}-fpm.sock
  when: ansible_distribution == 'Ubuntu'

- name: Create default site nginx config
  template:
    src: wordpress_nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  when: ansible_distribution == 'Ubuntu'

- name: Create default site nginx config
  template:
    src: wordpress_nginx.conf.j2
    dest: /etc/nginx/conf.d/wordpress_nginx.conf
  notify: restart nginx
  when: ansible_distribution == 'CentOS'

- name: Create nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  when: ansible_distribution == 'CentOS'

- name: Update user and group for /var/lib/php
  file:
    state: directory
    path: "/var/lib/php"
    owner: root
    group: nginx
    recurse: yes
  when: ansible_distribution == 'CentOS'

- name: Restart php-FPM
  service:
    name: php-fpm
    state: restarted
  when: ansible_distribution == 'CentOS'

- name: Open 80 port
  iptables:
    chain: INPUT
    in_interface: eth0
    protocol: tcp
    destination_port: '80'
    jump: ACCEPT

- name: restart nginx
  service:
    name: nginx
    state: restarted
