---
# nginx
- name: Check PHP version
  command: php --version
  register: php_version

- debug:
    var: php_version.stdout

- set_fact:
    fpm_sock: /run/php/php7.{{ php_version.stdout.split(" ")[1].split(".")[1] }}-fpm.sock

- name: Install nginx
  package:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Create project folder
  file:
    dest: /etc/nginx/sites-available
    state: directory

- name: Create nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
